    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_besar;
import javax.swing.*;
import java.sql.*;
import java.awt.Font;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;




/**
 *
 * @author Salman Faris A
 */
public class daftar_game extends javax.swing.JFrame {

    koneksi dbsetting;
    String driver,database,user,pass;
    Object tabel;
    
    /**
     * Creates new form daftar_game
     */
    public daftar_game() {
        initComponents();
        
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
 
        game.setModel(tableModel);
        settableload();
        
        game.getTableHeader().setFont(new Font("Poppins", Font.BOLD, 12));
        game.getTableHeader().setOpaque(false);
        game.getTableHeader().setBackground(new Color(43,43,48));
        game.getTableHeader().setForeground(new Color(239,239,239));
        
        btn_index.setEnabled(false);
    }
    
    private javax.swing.table.DefaultTableModel tableModel = getDefaultTableModel();
    private javax.swing.table.DefaultTableModel getDefaultTableModel() {
        return new javax.swing.table.DefaultTableModel (new Object[] [] {}, new String [] {"ID", "Nama Game", "Developer", "Genre", "Harga"}) 
        {
            boolean[] canEdit = new boolean[] {
                false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    }
    
    String data[] = new String[5];
    private void settableload() {
        String stat = "";
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "select * from game";
            ResultSet res = stt.executeQuery(SQL);
            while(res.next()) {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                tableModel.addRow(data);
                DefaultTableCellRenderer centerRenderer = new CenterTableCellRenderer();
                for (int i = 0; i < game.getColumnCount(); i++) {
                    game.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                }


            }
            res.close();
            stt.close();
            kon.close();
        }
        catch (Exception ex) {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        game = new javax.swing.JTable();
        txt_cari = new tugas_besar.G_FButton_0();
        btn_tambah = new tugas_besar.G_FButton_0();
        jPanel1 = new javax.swing.JPanel();
        btn_transaksi = new tugas_besar.G_FButton_2();
        btn_data = new tugas_besar.G_FButton_2();
        btn_index = new tugas_besar.G_FButton_2();
        btn_logout = new tugas_besar.G_FButton_2();
        btn_update = new tugas_besar.G_FButton_0();
        btn_hapus = new tugas_besar.G_FButton_1();
        txt_cari_data = new tugas_besar.FTextField_game();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("form_game");
        setBackground(new java.awt.Color(18, 18, 18));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menu.setBackground(new java.awt.Color(44, 47, 51));

        game.setBackground(new java.awt.Color(72, 72, 72));
        game.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        game.setForeground(new java.awt.Color(239, 239, 239));
        game.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        game.setToolTipText("");
        game.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        game.setFocusable(false);
        game.setRowHeight(35);
        game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(game);

        txt_cari.setBackground(new java.awt.Color(10, 10, 10));
        txt_cari.setForeground(new java.awt.Color(239, 239, 239));
        txt_cari.setText("Search");
        txt_cari.setFocusCycleRoot(true);
        txt_cari.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        btn_tambah.setForeground(new java.awt.Color(239, 239, 239));
        btn_tambah.setText("Add Game");
        btn_tambah.setFocusCycleRoot(true);
        btn_tambah.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(80, 113, 229));

        btn_transaksi.setText("Transaction");
        btn_transaksi.setFillClick(new java.awt.Color(80, 80, 229));
        btn_transaksi.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });

        btn_data.setText("Data");
        btn_data.setFillClick(new java.awt.Color(80, 80, 229));
        btn_data.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });

        btn_index.setText("Index");
        btn_index.setFillClick(new java.awt.Color(80, 80, 229));
        btn_index.setFocusable(false);
        btn_index.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N

        btn_logout.setText("Log Out");
        btn_logout.setFillClick(new java.awt.Color(80, 80, 229));
        btn_logout.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_data, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_index, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_data, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_index, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_update.setForeground(new java.awt.Color(239, 239, 239));
        btn_update.setText("Update");
        btn_update.setFocusCycleRoot(true);
        btn_update.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_hapus.setForeground(new java.awt.Color(239, 239, 239));
        btn_hapus.setText("Delete");
        btn_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        txt_cari_data.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        txt_cari_data.setForeground(new java.awt.Color(204, 204, 204));
        txt_cari_data.setText("Search");
        txt_cari_data.setCaretColor(new java.awt.Color(239, 239, 239));
        txt_cari_data.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        txt_cari_data.setMargin(new java.awt.Insets(10, 10, 10, 10));
        txt_cari_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cari_dataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cari_dataFocusLost(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(txt_cari_data, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_data, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1302, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        String cari = txt_cari_data.getText();
        
        if(cari.isEmpty() ) {
            tableModel.setRowCount(0);
            settableload();
        }
        else {
            try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "select * from game where Nama LIKE '%" 
                    + txt_cari_data.getText() + "%' or ID LIKE '%" 
                    + txt_cari_data.getText() + "%' or Developer LIKE '%" 
                    + txt_cari_data.getText() + "%' or Genre LIKE '%" 
                    + txt_cari_data.getText() + "%'";

            ResultSet res = stt.executeQuery(SQL);
            while(res.next()) {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                tableModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
        }
        catch (Exception ex) {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
      }  
        
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        tambah_game1 add = new tambah_game1();
        add.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int row = 0;
        ubah_game update = new ubah_game();
        row = game.getSelectedRow();
        update.txt_id.setText(tableModel.getValueAt(row, 0).toString());
        update.txt_nama_game.setText(tableModel.getValueAt(row,1).toString());
        update.txt_developer.setText(tableModel.getValueAt(row,2).toString());
        update.txt_genre.setText(tableModel.getValueAt(row, 3).toString());
        update.txt_harga.setText(tableModel.getValueAt(row, 4).toString());
        update.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int row = game.getSelectedRow();
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "DELETE From game " 
                            + "Where "
                        + "ID='"+tableModel.getValueAt(row, 0).toString()+"'";
            tableModel.removeRow(row);
            if(stt.executeUpdate(SQL) > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                }
                else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
                }
            stt.close();
            kon.close();
        }
        catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void gameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gameMouseClicked

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
        transaction_frm trans = new transaction_frm();
        trans.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void txt_cari_dataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cari_dataFocusGained
        // TODO add your handling code here:
        if(txt_cari_data.getText().equals("Search")) {
            txt_cari_data.setText("");
            txt_cari_data.setForeground(new Color(239,239,239));
        }

    }//GEN-LAST:event_txt_cari_dataFocusGained

    private void txt_cari_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cari_dataFocusLost
        // TODO add your handling code here:
        if(txt_cari_data.getText().equals("")) {
            txt_cari_data.setText("");
            txt_cari_data.setForeground(new Color(239,239,239));
        }
    }//GEN-LAST:event_txt_cari_dataFocusLost

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        frm_login_admin admin = new frm_login_admin();
        admin.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        // TODO add your handling code here:
        frm_select_data data = new frm_select_data();
        data.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar_game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tugas_besar.G_FButton_2 btn_data;
    private tugas_besar.G_FButton_1 btn_hapus;
    private tugas_besar.G_FButton_2 btn_index;
    private tugas_besar.G_FButton_2 btn_logout;
    private tugas_besar.G_FButton_0 btn_tambah;
    private tugas_besar.G_FButton_2 btn_transaksi;
    private tugas_besar.G_FButton_0 btn_update;
    private javax.swing.JTable game;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    private tugas_besar.G_FButton_0 txt_cari;
    private tugas_besar.FTextField_game txt_cari_data;
    // End of variables declaration//GEN-END:variables
}
