/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_besar;

import java.awt.Color;
/**
 *
 * @author radit
 */
import javax.swing.*;
import java.sql.*;
import java.awt.Font;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;

class CenterTableCellRenderer extends DefaultTableCellRenderer {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        
        // Mengatur perataan isi tabel menjadi di tengah
        ((DefaultTableCellRenderer) c).setHorizontalAlignment(SwingConstants.CENTER);
        
        return c;
    }
}

public class frm_user_utama extends javax.swing.JFrame  {
    koneksi dbsetting;
    String driver,database,user,pass;
    Object tabel;

    /**
     * Creates new form frm_user1_utama
     */
    public static String email2; 
    public frm_user_utama() {
        initComponents();
        
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
 
        game.setModel(tableModel);
        settableload();
        
        game.getTableHeader().setFont(new Font("Poppins", Font.BOLD, 12));
        game.getTableHeader().setOpaque(false);
        game.getTableHeader().setBackground(new Color(43,43,48));
        game.getTableHeader().setForeground(new Color(239,239,239));
        
        btn_home.setEnabled(false);
        
       
    }
    private javax.swing.table.DefaultTableModel tableModel = getDefaultTableModel();
    private javax.swing.table.DefaultTableModel getDefaultTableModel() {
        return new javax.swing.table.DefaultTableModel (new Object[] [] {}, new String [] {"ID", "Nama Game", "Developer", "Genre", "Harga"}) 
        {
            boolean[] canEdit = new boolean[] {
                false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
         };
     }
    String data[] = new String[5];
    private void settableload() {
        String stat = "";
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "select * from game";
            ResultSet res = stt.executeQuery(SQL);
            while(res.next()) {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                tableModel.addRow(data);
                DefaultTableCellRenderer centerRenderer = new CenterTableCellRenderer();
                for (int i = 0; i < game.getColumnCount(); i++) {
                game.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
}
            }
            
            res.close();
            stt.close();
            kon.close();
        }
        catch (Exception ex) {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            
            System.exit(0);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new tugas_besar.U_FButton1();
        btn_libraries = new tugas_besar.U_FButton1();
        btn_logOut = new tugas_besar.U_FButton1();
        profile = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        game = new javax.swing.JTable();
        btn_searchGame = new tugas_besar.U_FButton2();
        fButton21 = new tugas_besar.U_FButton2();
        txt_searchGame = new tugas_besar.FextField_user();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 47, 51));

        jPanel2.setBackground(new java.awt.Color(80, 113, 229));
        jPanel2.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N

        btn_home.setForeground(new java.awt.Color(239, 239, 239));
        btn_home.setText("Home");
        btn_home.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        btn_home.setLineOver(new java.awt.Color(80, 113, 229));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_libraries.setText("My Libraries");
        btn_libraries.setToolTipText("");
        btn_libraries.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        btn_libraries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_librariesActionPerformed(evt);
            }
        });

        btn_logOut.setText("Log Out");
        btn_logOut.setFont(new java.awt.Font("Trebuchet MS", 1, 26)); // NOI18N
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_besar/icons8-user-48.png"))); // NOI18N

        email.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(239, 239, 239));
        email.setText("email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(profile)))
                .addGap(38, 38, 38)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_libraries, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(btn_logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_libraries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        game.setBackground(new java.awt.Color(72, 72, 72));
        game.setForeground(new java.awt.Color(239, 239, 239));
        game.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        game.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        game.setRowHeight(30);
        jScrollPane1.setViewportView(game);

        btn_searchGame.setBackground(new java.awt.Color(80, 113, 229));
        btn_searchGame.setText("Search");
        btn_searchGame.setFillClick(new java.awt.Color(80, 80, 229));
        btn_searchGame.setFillOver(new java.awt.Color(80, 95, 229));
        btn_searchGame.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_searchGame.setLineOriginal(new java.awt.Color(80, 113, 229));
        btn_searchGame.setLineOver(new java.awt.Color(80, 80, 229));
        btn_searchGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchGameActionPerformed(evt);
            }
        });

        fButton21.setBackground(new java.awt.Color(80, 113, 229));
        fButton21.setText("Purchase");
        fButton21.setFillClick(new java.awt.Color(80, 80, 229));
        fButton21.setFillOriginal(new java.awt.Color(80, 113, 229));
        fButton21.setFillOver(new java.awt.Color(80, 95, 229));
        fButton21.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        fButton21.setLineOriginal(new java.awt.Color(80, 113, 229));
        fButton21.setLineOver(new java.awt.Color(80, 95, 229));
        fButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton21ActionPerformed(evt);
            }
        });

        txt_searchGame.setForeground(new java.awt.Color(204, 204, 204));
        txt_searchGame.setText("Search");
        txt_searchGame.setToolTipText("");
        txt_searchGame.setCaretColor(new java.awt.Color(239, 239, 239));
        txt_searchGame.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_searchGame.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchGameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchGameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_searchGame, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_searchGame, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_searchGame, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_searchGame, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(fButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        // TODO add your handling code here:
        frm_login log = new frm_login();
        log.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_logOutActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_librariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_librariesActionPerformed
        // TODO add your handling code here:
        email2 = email.getText();
        frm_user_library lib = new frm_user_library();
 
        lib.setVisible(true);

        //menghilangkan form utama
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_librariesActionPerformed

    private void btn_searchGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchGameActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        String cari = txt_searchGame.getText();
        
        if(cari.isEmpty() ) {
            tableModel.setRowCount(0);
            settableload();
        }
        else {
            try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            Statement stt = kon.createStatement();
            String SQL = "select * from game where Nama LIKE '%" + txt_searchGame.getText() + "%' OR ID LIKE '%" 
                         + txt_searchGame.getText() + "%' OR Developer LIKE '%" + txt_searchGame.getText() 
                         + "%' OR Genre LIKE '%" + txt_searchGame.getText() + "%'  ";

            ResultSet res = stt.executeQuery(SQL);
            while(res.next()) {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                data[4] = res.getString(5);
                tableModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
        }
        catch (Exception ex) {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
      }
    }//GEN-LAST:event_btn_searchGameActionPerformed

    private void fButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton21ActionPerformed
        // TODO add your handling code here:
        int row = 0;
        frm_purchase buy = new frm_purchase();
        row = game.getSelectedRow();
        buy.txt_id.setText(tableModel.getValueAt(row, 0).toString());
        buy.txt_game.setText(tableModel.getValueAt(row,1).toString());
        buy.txt_developer.setText(tableModel.getValueAt(row,2).toString());
        buy.txt_genre.setText(tableModel.getValueAt(row, 3).toString());
        buy.txt_harga.setText(tableModel.getValueAt(row, 4).toString());
        buy.setVisible(true);
        
        buy.txt_user_mail.setText(email.getText());
    }//GEN-LAST:event_fButton21ActionPerformed

    private void txt_searchGameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchGameFocusGained
        // TODO add your handling code here:
        if(txt_searchGame.getText().equals("Search")) {
            txt_searchGame.setText("");
            txt_searchGame.setForeground(new Color(239,239,239));}
    }//GEN-LAST:event_txt_searchGameFocusGained

    private void txt_searchGameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchGameFocusLost
        // TODO add your handling code here:
        if(txt_searchGame.getText().equals("")) {
            txt_searchGame.setText("");
            txt_searchGame.setForeground(new Color(239,239,239));
        }
    }//GEN-LAST:event_txt_searchGameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_user_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_user_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_user_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_user_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_user_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tugas_besar.U_FButton1 btn_home;
    private tugas_besar.U_FButton1 btn_libraries;
    private tugas_besar.U_FButton1 btn_logOut;
    private tugas_besar.U_FButton2 btn_searchGame;
    public javax.swing.JLabel email;
    private tugas_besar.U_FButton2 fButton21;
    private javax.swing.JTable game;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel profile;
    private tugas_besar.FextField_user txt_searchGame;
    // End of variables declaration//GEN-END:variables
}
